### ISSUE TITLE
NPE from mmoCore/Party

### ISSUE THREAD

**Issue by Dockter** [mmoMinecraftDev/mmoCore#15] opened 2012-02-03 19:29 UTC
See Below:

org.bukkit.command.CommandException: Unhandled exception executing command 'party' in plugin mmoParty v1.5  
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)  
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)  
at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:473)  
at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:777)  
at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:737)  
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:725)  
at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:176)  
at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)  
at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)  
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)  
at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:552)  
at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)  
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:537)  
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)  
at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)  
Caused by: java.lang.NullPointerException  
at mmo.Core.MMOPlugin.setData(MMOPlugin.java:676)  
at mmo.Core.MMOPlugin.setString(MMOPlugin.java:726)  
at mmo.Party.PartyAPI.save(PartyAPI.java:133)  
at mmo.Party.PartyAPI.leave(PartyAPI.java:352)  
at mmo.Party.MMOParty.onCommand(MMOParty.java:234)  
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)

**Comment by Dockter** [comment] 2012-02-08 19:16
Still getting these:

Also, this is a new one:

2012-02-08 11:50:10 [SEVERE] null 
org.bukkit.command.CommandException: Unhandled exception executing command 'party' in plugin mmoParty v1.5  
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)  
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)  
at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:473)  
at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:777)  
at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:737)  
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:725)  
at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:176)  
at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)  
at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)  
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)  
at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:552)  
at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)  
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:537)  
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)  
at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)  
Caused by: java.lang.NullPointerException  
at mmo.Core.MMOPlugin.setData(MMOPlugin.java:676)  
at mmo.Core.MMOPlugin.setStringList(MMOPlugin.java:751)  
at mmo.Party.PartyAPI.save(PartyAPI.java:137)  
at mmo.Party.PartyAPI.remove(PartyAPI.java:308)  
at mmo.Party.PartyAPI.leave(PartyAPI.java:347)  
at mmo.Party.MMOParty.onCommand(MMOParty.java:234)  
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)

**Comment by Xaymar** [comment] 2012-02-08 21:24
Will look into it.

**Comment by lukespragg** [comment] 2012-05-17 01:45
Duplicate of https://github.com/mmoMinecraftDev/mmoParty/issues/11.

**Closed as completed by lukespragg** 2012-05-17 01:45 UTC
Labels: Bug, ToDo
